#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc ]; then
	global.boot.default="mmc nand net"
elif [ $bootsource = nand ]; then
	global.boot.default="nand mmc net"
elif [ $bootsource = net ]; then
	global.boot.default="net nand mmc"
fi
